# Generated by Django 4.1.2 on 2022-11-26 21:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightoperator',
            name='email',
        ),
        migrations.AddField(
            model_name='flightoperator',
            name='department',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
