# Generated by Django 4.1.2 on 2022-11-26 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fo', '0002_remove_flightoperator_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightoperator',
            name='SimList',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
