# Generated by Django 4.1.2 on 2022-12-01 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fo', '0002_sim_remove_flightoperator_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sim',
        ),
    ]
