# Generated by Django 4.1.2 on 2022-12-02 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tc', '0003_testconductor'),
        ('fo', '0003_delete_sim'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightoperator',
            name='sim_list',
            field=models.ManyToManyField(to='tc.sim', verbose_name='Sim'),
        ),
    ]
