# Generated by Django 4.1.2 on 2023-02-13 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fo', '0005_post_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
