# Generated by Django 4.1.2 on 2023-02-16 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fo', '0006_alter_flightoperator_sim_list'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
