# Generated by Django 4.1.2 on 2023-02-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simapp', '0003_alter_mission_options'),
        ('fo', '0007_delete_like_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightoperator',
            name='sim_list',
            field=models.ManyToManyField(blank=True, to='simapp.sim', verbose_name='Sim'),
        ),
    ]
