# Generated by Django 4.1.2 on 2023-03-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tc', '0024_alter_class_code_alter_class_flight_operators_and_more'),
        ('fo', '0008_alter_flightoperator_sim_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightoperator',
            name='class_list',
            field=models.ManyToManyField(blank=True, to='tc.class', verbose_name='Class'),
        ),
    ]
