# Generated by Django 4.1.2 on 2023-02-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fo', '0005_post_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subsystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys_name', models.CharField(default='', max_length=15)),
                ('button_value', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TCS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_working', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sim_name', models.CharField(default='', max_length=15)),
                ('flight_operators', models.ManyToManyField(to='fo.flightoperator', verbose_name='Flight Operators')),
                ('sys_list', models.ManyToManyField(to='simapp.subsystem')),
            ],
        ),
    ]
