# Generated by Django 4.1.2 on 2023-02-24 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simapp', '0002_mission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mission',
            options={},
        ),
    ]
