# Generated by Django 4.1.2 on 2023-02-27 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simapp', '0003_alter_mission_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoolSubsystem',
            fields=[
                ('subsystem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simapp.subsystem')),
                ('value', models.BooleanField(default=True)),
            ],
            bases=('simapp.subsystem',),
        ),
    ]
