# Generated by Django 4.1.2 on 2023-02-27 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simapp', '0004_boolsubsystem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoolSubsystem',
        ),
    ]
