# Generated by Django 4.1.2 on 2023-02-28 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simapp', '0005_delete_boolsubsystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsystem',
            name='input',
            field=models.CharField(choices=[('number', 'number'), ('range', 'range'), ('reset', 'reset'), ('submit', 'submit'), ('text', 'text'), ('checkbox', 'checkbox')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='subsystem',
            name='value',
            field=models.CharField(default='', max_length=15),
        ),
    ]
