# Generated by Django 4.1.2 on 2023-02-28 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simapp', '0006_subsystem_input_subsystem_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsystem',
            name='button_value',
        ),
    ]
