# Generated by Django 4.1.2 on 2023-03-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simapp', '0007_remove_subsystem_button_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='sim',
            name='command',
            field=models.CharField(default='', max_length=15),
        ),
    ]
