# Generated by Django 4.1.2 on 2023-03-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simapp', '0008_sim_command'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sim',
            name='command',
        ),
        migrations.RemoveField(
            model_name='subsystem',
            name='input',
        ),
        migrations.RemoveField(
            model_name='subsystem',
            name='value',
        ),
        migrations.AddField(
            model_name='subsystem',
            name='button_value',
            field=models.BooleanField(default=True),
        ),
    ]
