# Generated by Django 4.1.6 on 2023-03-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simapp', '0009_remove_sim_command_remove_subsystem_input_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACS_Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Buffer_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buffer_item', models.CharField(default='', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Console_Buffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buffer_list', models.ManyToManyField(to='simapp.buffer_item', verbose_name='Buffer list')),
            ],
        ),
        migrations.CreateModel(
            name='Subsys_Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='TCS',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='test_conductor',
        ),
        migrations.RemoveField(
            model_name='sim',
            name='sys_list',
        ),
        migrations.AddField(
            model_name='sim',
            name='acs_subsys',
            field=models.ManyToManyField(to='simapp.subsystem', verbose_name='ACS Subsystem'),
        ),
        migrations.AddField(
            model_name='sim',
            name='mission_script',
            field=models.ManyToManyField(to='simapp.mission', verbose_name='Mission Script'),
        ),
        migrations.AddField(
            model_name='sim',
            name='command_buffer',
            field=models.ManyToManyField(to='simapp.console_buffer', verbose_name='console buffer'),
        ),
        migrations.AddField(
            model_name='subsystem',
            name='subsys_console_buffer',
            field=models.ManyToManyField(to='simapp.console_buffer', verbose_name='Subsystem Console buffer'),
        ),
        migrations.AddField(
            model_name='subsystem',
            name='subsys_menu',
            field=models.ManyToManyField(to='simapp.acs_menu', verbose_name='ACS Menu'),
        ),
    ]
