# Generated by Django 4.1.2 on 2023-03-04 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simapp', '0010_acs_menu_buffer_item_console_buffer_subsys_menu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sim',
            name='acs_subsys',
        ),
        migrations.RemoveField(
            model_name='sim',
            name='command_buffer',
        ),
        migrations.RemoveField(
            model_name='sim',
            name='mission_script',
        ),
        migrations.AddField(
            model_name='sim',
            name='mission_script',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='simapp.mission'),
        ),
    ]
