# Generated by Django 4.1.2 on 2023-03-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simapp', '0012_remove_subsystem_subsys_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='sim',
            name='acs_subsys',
            field=models.ManyToManyField(to='simapp.subsystem', verbose_name='ACS Subsystem'),
        ),
    ]
