# Generated by Django 4.1.2 on 2023-03-04 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simapp', '0013_sim_acs_subsys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sim',
            name='acs_subsys',
        ),
    ]
