# Generated by Django 4.1.2 on 2023-03-05 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fo', '0009_flightoperator_class_list'),
        ('simapp', '0014_remove_sim_acs_subsys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim',
            name='flight_operators',
            field=models.ManyToManyField(blank=True, to='fo.flightoperator', verbose_name='Flight Operators'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='mission_script',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='simapp.mission'),
        ),
    ]
