# Generated by Django 4.1.2 on 2023-03-05 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simapp', '0015_alter_sim_flight_operators'),
        ('simapp', '0015_alter_sim_flight_operators_alter_sim_mission_script'),
    ]

    operations = [
    ]
