# Generated by Django 4.1.2 on 2023-03-05 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simapp', '0016_allmissions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllMissions',
        ),
    ]
