# Generated by Django 4.1.2 on 2023-03-05 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simapp', '0016_merge_20230305_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim',
            name='mission_script',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='simapp.mission'),
        ),
    ]
