# Generated by Django 4.1.2 on 2023-03-05 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simapp', '0017_alter_sim_mission_script'),
        ('simapp', '0017_delete_allmissions'),
    ]

    operations = [
    ]
