# Generated by Django 4.1.2 on 2023-03-07 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simapp', '0019_alter_sim_mission_script'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim',
            name='mission_script',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simapp.mission'),
        ),
    ]
