# Generated by Django 4.1.2 on 2023-03-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tc', '0030_remove_class_missions_testconductor_missions'),
        ('simapp', '0022_remove_sim_flight_operators_sim_flight_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim',
            name='flight_director',
            field=models.ManyToManyField(blank=True, default='', to='tc.class', verbose_name='Flight Director'),
        ),
    ]
