# Generated by Django 4.1.2 on 2023-03-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fo', '0009_flightoperator_class_list'),
        ('simapp', '0023_alter_sim_flight_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim',
            name='flight_director',
            field=models.ManyToManyField(blank=True, default='', to='fo.flightoperator', verbose_name='Flight Director'),
        ),
    ]
