# Generated by Django 4.1.2 on 2023-03-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fo', '0009_flightoperator_class_list'),
        ('simapp', '0028_remove_sim_acs_fo_remove_sim_comms_fo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sim',
            name='flight_director',
            field=models.ManyToManyField(blank=True, default='', related_name='flight_director', to='fo.flightoperator', verbose_name='Flight Director'),
        ),
    ]
