# Generated by Django 4.1.2 on 2023-03-23 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simapp', '0029_sim_flight_director'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sim',
            name='flight_director',
        ),
    ]
