# Generated by Django 4.1.2 on 2023-03-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fo', '0009_flightoperator_class_list'),
        ('simapp', '0031_sim_flight_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='sim',
            name='ACS_fo',
            field=models.ManyToManyField(blank=True, default='', related_name='acs_fo', to='fo.flightoperator', verbose_name='ACS Flight Operator'),
        ),
        migrations.AddField(
            model_name='sim',
            name='COMMS_fo',
            field=models.ManyToManyField(blank=True, default='', related_name='comms_fo', to='fo.flightoperator', verbose_name='Comms Flight Operator'),
        ),
        migrations.AddField(
            model_name='sim',
            name='EPS_fo',
            field=models.ManyToManyField(blank=True, default='', related_name='eps_fo', to='fo.flightoperator', verbose_name='EPS Flight Operator'),
        ),
        migrations.AddField(
            model_name='sim',
            name='TCS_fo',
            field=models.ManyToManyField(blank=True, default='', related_name='tcs_fo', to='fo.flightoperator', verbose_name='TCS Flight Operator'),
        ),
    ]
