# Generated by Django 4.1.6 on 2023-04-11 20:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fo', '0009_flightoperator_class_list'),
        ('simapp', '0032_sim_acs_fo_sim_comms_fo_sim_eps_fo_sim_tcs_fo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subsys_Menu',
        ),
        migrations.RemoveField(
            model_name='subsystem',
            name='command_buffer',
        ),
        migrations.RemoveField(
            model_name='sim',
            name='display_buffer',
        ),
        migrations.RemoveField(
            model_name='sim',
            name='sys_list',
        ),
        migrations.AddField(
            model_name='mission',
            name='final_pitch',
            field=models.IntegerField(blank=True, default=87, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='mission',
            name='final_roll',
            field=models.IntegerField(blank=True, default=-23, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AddField(
            model_name='mission',
            name='final_yaw',
            field=models.IntegerField(blank=True, default=-118, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AddField(
            model_name='sim',
            name='fo_list',
            field=models.ManyToManyField(to='fo.flightoperator'),
        ),
        migrations.AddField(
            model_name='sim',
            name='sim_identifier',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='sim',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('COMPLETE', 'COMPLETE')], default='ACTIVE', max_length=15),
        ),
        migrations.AlterField(
            model_name='sim',
            name='flight_director',
            field=models.ManyToManyField(blank=True, default='', related_name='flight_director', to='fo.flightoperator', verbose_name='Flight Director (Payload Flight Operator)'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='sim_name',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.DeleteModel(
            name='CommandBufferItem',
        ),
        migrations.DeleteModel(
            name='DisplayBufferItem',
        ),
        migrations.DeleteModel(
            name='Subsystem',
        ),
    ]
