# Generated by Django 4.1.6 on 2023-04-19 23:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simapp', '0039_mission_verbose_name_alter_mission_final_pitch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='final_pitch',
            field=models.IntegerField(blank=True, default=44, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='mission',
            name='final_roll',
            field=models.IntegerField(blank=True, default=-133, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='mission',
            name='final_yaw',
            field=models.IntegerField(blank=True, default=22, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
    ]
