# Generated by Django 4.1.2 on 2023-03-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayBufferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buffer_item', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.RenameModel(
            old_name='BufferItem',
            new_name='CommandBufferItem',
        ),
        migrations.AddField(
            model_name='sim',
            name='command_buffer',
            field=models.ManyToManyField(blank=True, to='testapp.commandbufferitem', verbose_name='command buffer'),
        ),
        migrations.AddField(
            model_name='sim',
            name='display_buffer',
            field=models.ManyToManyField(blank=True, to='testapp.displaybufferitem', verbose_name='display buffer'),
        ),
    ]
