# Generated by Django 4.1.6 on 2023-04-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_mission'),
    ]

    operations = [
        migrations.AddField(
            model_name='sim',
            name='sim_identifier',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
    ]
