# Generated by Django 4.1.2 on 2022-12-01 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sim_name', models.CharField(default='', max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='TestConductor',
        ),
    ]
