# Generated by Django 4.1.2 on 2022-12-02 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tc', '0004_remove_testconductor_tc_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testconductor',
            name='button_value',
        ),
        migrations.AddField(
            model_name='sim',
            name='button_value',
            field=models.BooleanField(default=True),
        ),
    ]
