# Generated by Django 4.1.2 on 2022-12-02 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tc', '0008_rename_sim_list_sim_sys_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sim',
            name='button_value',
        ),
    ]
