# Generated by Django 4.1.2 on 2022-12-02 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tc', '0010_alter_sim_sys_list'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SimSys',
            new_name='Subsystem',
        ),
    ]
