# Generated by Django 4.1.2 on 2022-12-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tc', '0012_sim_flight_operators'),
    ]

    operations = [
        migrations.AddField(
            model_name='testconductor',
            name='sim_list',
            field=models.ManyToManyField(to='tc.sim', verbose_name='Sim'),
        ),
    ]
