# Generated by Django 4.1.2 on 2022-12-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tc', '0013_testconductor_sim_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testconductor',
            name='sim_list',
        ),
        migrations.AddField(
            model_name='sim',
            name='class_belong',
            field=models.ManyToManyField(blank=True, to='tc.testconductor', verbose_name='Class'),
        ),
    ]
