# Generated by Django 4.1.2 on 2022-12-07 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tc', '0013_testconductor_sim_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=15)),
                ('status', models.CharField(default='', max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Classes',
            },
        ),
    ]
