# Generated by Django 4.1.2 on 2022-12-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tc', '0014_remove_testconductor_sim_list_sim_class_belong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim',
            name='class_belong',
            field=models.ManyToManyField(blank=True, to='auth.group', verbose_name='Class'),
        ),
    ]
