# Generated by Django 4.1.2 on 2022-12-08 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tc', '0015_alter_sim_class_belong'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sim',
            name='class_belong',
        ),
    ]
