# Generated by Django 4.1.2 on 2022-12-07 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tc', '0016_rename_name_class_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='sims',
            field=models.ManyToManyField(to='tc.sim', verbose_name='Sim'),
        ),
    ]
