# Generated by Django 4.1.2 on 2022-12-08 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tc', '0016_remove_sim_class_belong'),
        ('tc', '0017_class_sims'),
    ]

    operations = [
    ]
