# Generated by Django 4.1.2 on 2023-02-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fo', '0005_post_like'),
        ('tc', '0018_merge_0016_remove_sim_class_belong_0017_class_sims'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim',
            name='flight_operators',
            field=models.ManyToManyField(to='fo.flightoperator', verbose_name='Flight Operators'),
        ),
    ]
