# Generated by Django 4.1.2 on 2023-02-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simapp', '0001_initial'),
        #('auth', '0014_alter_group_sim_list'),
        ('fo', '0006_alter_flightoperator_sim_list'),
        ('tc', '0019_alter_sim_flight_operators'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='code',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='class',
            name='sims',
            field=models.ManyToManyField(to='simapp.sim', verbose_name='Sim'),
        ),
        migrations.DeleteModel(
            name='Sim',
        ),
        migrations.DeleteModel(
            name='Subsystem',
        ),
    ]
