# Generated by Django 4.1.2 on 2023-02-24 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tc', '0021_mission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mission',
        ),
    ]
