# Generated by Django 4.1.2 on 2023-02-24 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simapp', '0002_mission'),
        ('tc', '0022_delete_mission'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='missions',
            field=models.ManyToManyField(to='simapp.mission', verbose_name='Mission'),
        ),
    ]
