# Generated by Django 4.1.2 on 2023-02-24 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fo', '0007_delete_like_delete_post'),
        ('simapp', '0002_mission'),
        ('tc', '0023_class_missions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='code',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='class',
            name='flight_operators',
            field=models.ManyToManyField(blank=True, to='fo.flightoperator', verbose_name='Flight Operator'),
        ),
        migrations.AlterField(
            model_name='class',
            name='sims',
            field=models.ManyToManyField(blank=True, to='simapp.sim', verbose_name='Sim'),
        ),
        migrations.AlterField(
            model_name='class',
            name='status',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
