# Generated by Django 4.1.6 on 2023-03-04 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tc', '0024_alter_class_code_alter_class_flight_operators_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='missions',
        ),
        migrations.RemoveField(
            model_name='class',
            name='sims',
        ),
    ]
