# Generated by Django 4.1.2 on 2023-03-04 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tc', '0026_class_missions_class_sims'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='missions',
        ),
    ]
