# Generated by Django 4.1.2 on 2023-03-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simapp', '0014_remove_sim_acs_subsys'),
        ('tc', '0027_remove_class_missions'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='missions',
            field=models.ManyToManyField(to='simapp.mission', verbose_name='Mission'),
        ),
    ]
