# Generated by Django 4.1.6 on 2023-03-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simapp', '0014_remove_sim_acs_subsys'),
        ('tc', '0028_class_missions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='missions',
            field=models.ManyToManyField(blank=True, to='simapp.mission', verbose_name='Mission'),
        ),
    ]
