# Generated by Django 4.1.2 on 2023-03-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simapp', '0016_allmissions'),
        ('tc', '0029_alter_class_missions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='missions',
        ),
        migrations.AddField(
            model_name='testconductor',
            name='missions',
            field=models.ManyToManyField(blank=True, to='simapp.mission', verbose_name='Mission'),
        ),
    ]
