# Generated by Django 4.1.2 on 2023-03-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tc', '0030_remove_class_missions_testconductor_missions'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class2comp',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_name',
            field=models.CharField(default='', max_length=15, unique=True),
        ),
    ]
