# Generated by Django 4.1.6 on 2023-04-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tc', '0030_remove_class_missions_testconductor_missions'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='test',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='code',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='class',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('COMPLETE', 'COMPLETE')], default='ACTIVE', max_length=15),
        ),
    ]
