# Generated by Django 4.1.2 on 2023-03-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tc', '0031_class_class2comp_alter_class_class_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='class2comp',
        ),
        migrations.AlterField(
            model_name='class',
            name='class_name',
            field=models.CharField(default='', max_length=15),
        ),
    ]
