# Generated by Django 4.1.6 on 2023-04-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simapp', '0039_mission_verbose_name_alter_mission_final_pitch_and_more'),
        ('tc', '0032_class_tc_testconductor_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='sims',
        ),
        migrations.AddField(
            model_name='class',
            name='missions',
            field=models.ManyToManyField(blank=True, to='simapp.mission', verbose_name='Mission'),
        ),
    ]
